// Paste this file's contents below the two autogenerated header lines in a new
// Onshape Feature Studio. Keep the Onshape-generated `FeatureScript ...;` and
// `import(path : "onshape/std/geometry.fs", version : "...");` lines above it.
//
// Coordinate convention for this baseline:
// - +X points distally along the finger axis
// - +Y points toward the tendon-guide side
// - +Z points dorsally

const CAD_EPSILON = 0.1 * millimeter;

annotation { "Feature Type Name" : "Single Tendon Ring Thimble Set" }
export const singleTendonRingThimbleSet = defineFeature(function(context is Context, id is Id, definition is map)
    precondition
    {
        annotation { "Name" : "Proximal ring center X" }
        isLength(definition.proximalRingCenterX, LENGTH_BOUNDS);

        annotation { "Name" : "Middle ring center X" }
        isLength(definition.middleRingCenterX, LENGTH_BOUNDS);

        annotation { "Name" : "Guide ring inner diameter" }
        isLength(definition.guideRingInnerDiameter, LENGTH_BOUNDS);

        annotation { "Name" : "Guide ring length" }
        isLength(definition.guideRingLength, LENGTH_BOUNDS);

        annotation { "Name" : "Guide ring wall" }
        isLength(definition.guideRingWall, LENGTH_BOUNDS);

        annotation { "Name" : "Guide ring split width" }
        isLength(definition.guideRingSplitWidth, LENGTH_BOUNDS);

        annotation { "Name" : "Tendon channel diameter" }
        isLength(definition.tendonChannelDiameter, LENGTH_BOUNDS);

        annotation { "Name" : "Tendon guide offset Y" }
        isLength(definition.tendonGuideOffsetY, LENGTH_BOUNDS);

        annotation { "Name" : "Tendon guide offset Z" }
        isLength(definition.tendonGuideOffsetZ, LENGTH_BOUNDS);

        annotation { "Name" : "Guide boss wall" }
        isLength(definition.guideBossWall, LENGTH_BOUNDS);

        annotation { "Name" : "Thimble start X" }
        isLength(definition.thimbleStartX, LENGTH_BOUNDS);

        annotation { "Name" : "Thimble inner diameter" }
        isLength(definition.thimbleInnerDiameter, LENGTH_BOUNDS);

        annotation { "Name" : "Thimble length" }
        isLength(definition.thimbleLength, LENGTH_BOUNDS);

        annotation { "Name" : "Thimble wall" }
        isLength(definition.thimbleWall, LENGTH_BOUNDS);

        annotation { "Name" : "Thimble tip cap" }
        isLength(definition.thimbleTipCap, LENGTH_BOUNDS);

        annotation { "Name" : "Thimble split width" }
        isLength(definition.thimbleSplitWidth, LENGTH_BOUNDS);

        annotation { "Name" : "Anchor hole diameter" }
        isLength(definition.anchorHoleDiameter, LENGTH_BOUNDS);
    }
    {
        validateRingThimbleDefinition(definition);

        makeGuideRing(
                context,
                id + "proximalRing",
                definition.proximalRingCenterX,
                definition.guideRingInnerDiameter,
                definition.guideRingLength,
                definition.guideRingWall,
                definition.guideRingSplitWidth,
                definition.tendonChannelDiameter,
                definition.tendonGuideOffsetY,
                definition.tendonGuideOffsetZ,
                definition.guideBossWall);

        makeGuideRing(
                context,
                id + "middleRing",
                definition.middleRingCenterX,
                definition.guideRingInnerDiameter,
                definition.guideRingLength,
                definition.guideRingWall,
                definition.guideRingSplitWidth,
                definition.tendonChannelDiameter,
                definition.tendonGuideOffsetY,
                definition.tendonGuideOffsetZ,
                definition.guideBossWall);

        makeDistalThimble(
                context,
                id + "distalThimble",
                definition.thimbleStartX,
                definition.thimbleInnerDiameter,
                definition.thimbleLength,
                definition.thimbleWall,
                definition.thimbleTipCap,
                definition.thimbleSplitWidth,
                definition.tendonChannelDiameter,
                definition.tendonGuideOffsetY,
                definition.tendonGuideOffsetZ,
                definition.guideBossWall,
                definition.anchorHoleDiameter);
    });

function validateRingThimbleDefinition(definition is map)
{
    if (definition.middleRingCenterX <= definition.proximalRingCenterX)
        throw regenError("Middle ring center X must be distal to the proximal ring center X",
                ["proximalRingCenterX", "middleRingCenterX"]);

    if (definition.middleRingCenterX - definition.proximalRingCenterX < definition.guideRingLength)
        throw regenError("Guide rings overlap in X", ["proximalRingCenterX", "middleRingCenterX", "guideRingLength"]);

    if (definition.thimbleStartX < definition.middleRingCenterX + definition.guideRingLength / 2)
        throw regenError("Thimble start X overlaps the middle ring", ["thimbleStartX", "middleRingCenterX", "guideRingLength"]);

    if (hypot(definition.tendonGuideOffsetY, definition.tendonGuideOffsetZ) <=
            definition.guideRingInnerDiameter / 2 + definition.tendonChannelDiameter / 2)
        throw regenError("Guide channel intersects the ring finger bore",
                ["tendonGuideOffsetY", "tendonGuideOffsetZ", "guideRingInnerDiameter", "tendonChannelDiameter"]);

    if (hypot(definition.tendonGuideOffsetY, definition.tendonGuideOffsetZ) <=
            definition.thimbleInnerDiameter / 2 + definition.tendonChannelDiameter / 2)
        throw regenError("Guide channel intersects the thimble finger bore",
                ["tendonGuideOffsetY", "tendonGuideOffsetZ", "thimbleInnerDiameter", "tendonChannelDiameter"]);

    if (definition.thimbleTipCap >= definition.thimbleLength)
        throw regenError("Thimble tip cap must be shorter than the thimble length",
                ["thimbleTipCap", "thimbleLength"]);
}

function makeGuideRing(context is Context, id is Id,
        centerX is ValueWithUnits,
        innerDiameter is ValueWithUnits,
        ringLength is ValueWithUnits,
        wall is ValueWithUnits,
        splitWidth is ValueWithUnits,
        tendonChannelDiameter is ValueWithUnits,
        tendonGuideOffsetY is ValueWithUnits,
        tendonGuideOffsetZ is ValueWithUnits,
        bossWall is ValueWithUnits)
{
    const innerRadius = innerDiameter / 2;
    const outerRadius = innerRadius + wall;
    const tendonChannelRadius = tendonChannelDiameter / 2;
    const startX = centerX - ringLength / 2;
    const endX = centerX + ringLength / 2;

    const bossMinY = min(-outerRadius, tendonGuideOffsetY - tendonChannelRadius - bossWall);
    const bossMaxY = max(outerRadius, tendonGuideOffsetY + tendonChannelRadius + bossWall);
    const bossMinZ = min(-outerRadius, tendonGuideOffsetZ - tendonChannelRadius - bossWall);
    const bossMaxZ = max(outerRadius, tendonGuideOffsetZ + tendonChannelRadius + bossWall);

    fCylinder(context, id + "outerBand", {
            "bottomCenter" : vector(startX, 0 * millimeter, 0 * millimeter),
            "topCenter" : vector(endX, 0 * millimeter, 0 * millimeter),
            "radius" : outerRadius
    });

    fCuboid(context, id + "guideBoss", {
            "corner1" : vector(startX, bossMinY, bossMinZ),
            "corner2" : vector(endX, bossMaxY, bossMaxZ)
    });

    opBoolean(context, id + "outerUnion", {
            "tools" : qUnion([
                qCreatedBy(id + "outerBand", EntityType.BODY),
                qCreatedBy(id + "guideBoss", EntityType.BODY)
            ]),
            "operationType" : BooleanOperationType.UNION
    });

    fCylinder(context, id + "fingerBore", {
            "bottomCenter" : vector(startX - CAD_EPSILON, 0 * millimeter, 0 * millimeter),
            "topCenter" : vector(endX + CAD_EPSILON, 0 * millimeter, 0 * millimeter),
            "radius" : innerRadius
    });

    fCylinder(context, id + "tendonChannel", {
            "bottomCenter" : vector(startX - CAD_EPSILON, tendonGuideOffsetY, tendonGuideOffsetZ),
            "topCenter" : vector(endX + CAD_EPSILON, tendonGuideOffsetY, tendonGuideOffsetZ),
            "radius" : tendonChannelRadius
    });

    fCuboid(context, id + "splitCut", {
            "corner1" : vector(startX - CAD_EPSILON, -splitWidth / 2, bossMinZ - CAD_EPSILON),
            "corner2" : vector(endX + CAD_EPSILON, splitWidth / 2, bossMaxZ + CAD_EPSILON)
    });

    opBoolean(context, id + "finalCut", {
            "tools" : qUnion([
                qCreatedBy(id + "fingerBore", EntityType.BODY),
                qCreatedBy(id + "tendonChannel", EntityType.BODY),
                qCreatedBy(id + "splitCut", EntityType.BODY)
            ]),
            "targets" : qCreatedBy(id + "outerUnion", EntityType.BODY),
            "operationType" : BooleanOperationType.SUBTRACTION
    });
}

function makeDistalThimble(context is Context, id is Id,
        startX is ValueWithUnits,
        innerDiameter is ValueWithUnits,
        thimbleLength is ValueWithUnits,
        wall is ValueWithUnits,
        tipCap is ValueWithUnits,
        splitWidth is ValueWithUnits,
        tendonChannelDiameter is ValueWithUnits,
        tendonGuideOffsetY is ValueWithUnits,
        tendonGuideOffsetZ is ValueWithUnits,
        bossWall is ValueWithUnits,
        anchorHoleDiameter is ValueWithUnits)
{
    const innerRadius = innerDiameter / 2;
    const outerRadius = innerRadius + wall;
    const tendonChannelRadius = tendonChannelDiameter / 2;
    const anchorHoleRadius = anchorHoleDiameter / 2;
    const endX = startX + thimbleLength;
    const boreEndX = endX - tipCap;
    const anchorHoleCenterX = endX - tipCap / 2;

    const bossMinY = min(-outerRadius, tendonGuideOffsetY - tendonChannelRadius - bossWall);
    const bossMaxY = max(outerRadius, tendonGuideOffsetY + tendonChannelRadius + bossWall);
    const bossMinZ = min(-outerRadius, tendonGuideOffsetZ - tendonChannelRadius - bossWall);
    const bossMaxZ = max(outerRadius, tendonGuideOffsetZ + tendonChannelRadius + bossWall);

    fCylinder(context, id + "outerShell", {
            "bottomCenter" : vector(startX, 0 * millimeter, 0 * millimeter),
            "topCenter" : vector(endX, 0 * millimeter, 0 * millimeter),
            "radius" : outerRadius
    });

    fCuboid(context, id + "guideBoss", {
            "corner1" : vector(startX, bossMinY, bossMinZ),
            "corner2" : vector(endX, bossMaxY, bossMaxZ)
    });

    opBoolean(context, id + "outerUnion", {
            "tools" : qUnion([
                qCreatedBy(id + "outerShell", EntityType.BODY),
                qCreatedBy(id + "guideBoss", EntityType.BODY)
            ]),
            "operationType" : BooleanOperationType.UNION
    });

    fCylinder(context, id + "fingerBore", {
            "bottomCenter" : vector(startX - CAD_EPSILON, 0 * millimeter, 0 * millimeter),
            "topCenter" : vector(boreEndX, 0 * millimeter, 0 * millimeter),
            "radius" : innerRadius
    });

    fCylinder(context, id + "tendonChannel", {
            "bottomCenter" : vector(startX - CAD_EPSILON, tendonGuideOffsetY, tendonGuideOffsetZ),
            "topCenter" : vector(anchorHoleCenterX, tendonGuideOffsetY, tendonGuideOffsetZ),
            "radius" : tendonChannelRadius
    });

    fCylinder(context, id + "anchorHole", {
            "bottomCenter" : vector(anchorHoleCenterX, bossMinY - CAD_EPSILON, tendonGuideOffsetZ),
            "topCenter" : vector(anchorHoleCenterX, bossMaxY + CAD_EPSILON, tendonGuideOffsetZ),
            "radius" : anchorHoleRadius
    });

    fCuboid(context, id + "splitCut", {
            "corner1" : vector(startX - CAD_EPSILON, -splitWidth / 2, bossMinZ - CAD_EPSILON),
            "corner2" : vector(endX + CAD_EPSILON, splitWidth / 2, bossMaxZ + CAD_EPSILON)
    });

    opBoolean(context, id + "finalCut", {
            "tools" : qUnion([
                qCreatedBy(id + "fingerBore", EntityType.BODY),
                qCreatedBy(id + "tendonChannel", EntityType.BODY),
                qCreatedBy(id + "anchorHole", EntityType.BODY),
                qCreatedBy(id + "splitCut", EntityType.BODY)
            ]),
            "targets" : qCreatedBy(id + "outerUnion", EntityType.BODY),
            "operationType" : BooleanOperationType.SUBTRACTION
    });
}
